#!/usr/bin/env python3
"""Regenerate app/tokens.css from project-docs/trevo-design-tokens.tokens.json.

Rerun this whenever the design tokens file changes:
    python3 scripts/tokens-to-css.py

Only emits color and typography tokens as Tailwind v4 `@theme` entries
(namespaces that don't collide with Tailwind's own scales). Numeric
spacing/size tokens are deliberately NOT emitted as `--spacing-*` theme
values: Tailwind v4's spacing scale is multiplier-based (e.g. `p-4` = 16px
by default), and our Figma size tokens are raw pixel values (`size/4` =
4px) — redefining `--spacing-4` would silently break that convention
project-wide. Use the literal pixel values directly as Tailwind arbitrary
values (e.g. `px-[42px]`, `gap-[32px]`) at each call site instead.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "project-docs" / "trevo-design-tokens.tokens.json"
OUT = ROOT / "app" / "tokens.css"

ALIAS_RE = re.compile(r"^\{([\w.-]+)\}$")


def resolve(data: dict, value):
    """Resolve a `{path.to.token}` alias string to its underlying value."""
    while isinstance(value, str):
        m = ALIAS_RE.match(value)
        if not m:
            break
        node = data
        for part in m.group(1).split("."):
            node = node[part]
        value = node["value"]
    return value


def hex_color(value: str) -> str:
    """8-digit #rrggbbaa -> 6-digit #rrggbb when fully opaque, else keep alpha."""
    if isinstance(value, str) and value.startswith("#") and len(value) == 9:
        if value[-2:].lower() == "ff":
            return value[:-2]
    return value


def slugify(*parts: str) -> str:
    return "-".join(parts)


def px(value: float) -> str:
    rounded = round(value, 2)
    if rounded == int(rounded):
        rounded = int(rounded)
    return f"{rounded}px"


def main() -> None:
    data = json.loads(SOURCE.read_text())

    lines = [
        "/* Generated by scripts/tokens-to-css.py — do not edit by hand. */",
        "",
        "@theme {",
        "  --font-metropolis: 'Metropolis', ui-sans-serif, system-ui, sans-serif;",
        "",
        "  /* CLAUDE.md's exact Desktop cutoff (1025px+; Mobile is 1024px and below) — not a stock Tailwind breakpoint. */",
        "  /* Base (unprefixed) utilities are mobile-first; use `desktop:` for the 1025px+ override. */",
        "  --breakpoint-desktop: 1025px;",
        "",
    ]

    lines.append("  /* Colors — project-docs/trevo-design-tokens.tokens.json: tokens.{fill,text,border} */")
    for category in ("fill", "text", "border"):
        for name, token in data["tokens"][category].items():
            value = hex_color(resolve(data, token["value"]))
            lines.append(f"  --color-{category}-{name}: {value};")
    lines.append("")

    gradient_lines = []
    for name, token in data["gradient"].items():
        stops = ", ".join(f"{s['color'][:7]} {round(s['position'] * 100)}%" for s in token["value"]["stops"])
        gradient_lines.append(f"  --gradient-{name}: linear-gradient({token['value']['rotation']}deg, {stops});")

    lines.append("  /* Typography — one Tailwind `text-*` utility per Figma type style, with paired */")
    lines.append("  /* line-height/letter-spacing/weight (Tailwind v4 --text-<name>--<prop> convention). */")
    for device in ("desktop", "mobile"):
        for category, variants in data["typography"][device].items():
            for variant, style in variants.items():
                name = slugify(device, category, variant)
                size = px(style["fontSize"]["value"])
                line_height = px(style["lineHeight"]["value"])
                letter_spacing = px(style["letterSpacing"]["value"])
                weight = style["fontWeight"]["value"]
                lines.append(f"  --text-{name}: {size};")
                lines.append(f"  --text-{name}--line-height: {line_height};")
                lines.append(f"  --text-{name}--letter-spacing: {letter_spacing};")
                lines.append(f"  --text-{name}--font-weight: {weight};")
    lines.append("}")
    lines.append("")
    lines.append(":root {")
    lines.append("  /* Gradients as plain custom properties (not a Tailwind theme namespace). */")
    lines.append("  /* Reference one with a Tailwind arbitrary background-image value pointing at --gradient-<name>. */")
    lines.extend(gradient_lines)
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
